version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.3.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/cpp/rest
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/rest/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ BasePlatform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ XML"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/xml.git && cd xml/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ TestFramework/Core"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/test-framework.git && cd test-framework/core/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/rest/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/rest/tests/build/gnumake && ./IshikoRESTTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/IshikoREST.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/IshikoREST.xml
          destination: IshikoREST-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/IshikoREST.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
